# Generated by Django 2.2.7 on 2019-11-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pika', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='lighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tree',
            name='look',
            field=models.IntegerField(choices=[(1, 'クール'), (2, 'かわいい'), (3, 'おしゃれ'), (4, 'ばえ'), (5, '読める！'), (6, 'おもしろい')]),
        ),
    ]
