# Generated by Django 2.2.4 on 2019-12-14 10:41

from django.db import migrations
import pika.models


class Migration(migrations.Migration):

    dependencies = [
        ('pika', '0002_auto_20191128_1537'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pika.models.CustomUserManager()),
            ],
        ),
    ]
